config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments

    member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
    end
  end

  get 'static_pages/contact' => 'static_pages#contact', as: 'contact'

  get 'static_pages/about' => 'static_pages#about', as: 'about'

  get 'sessions/login'

  get 'sessions/logout' => 'sessions#logout', as: 'sessions_logout'

  post 'sessions' => 'sessions#create'

  resources :posts

  
  get 'registration' => 'users#new', as: 'registration'  # = get 'registration' => 'users#new'

  post 'users' => 'users#create'

  get 'users/:id' => 'users#show'

  resources :users

   root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user

	has_many :composts

	has_ancestry

	validates_presence_of :post_id


	after_create :update_post
  def update_post
    self.post.touch
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :set_comment, only: [:show, :create, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /comments
  # GET /comments.json
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    
  end

  # GET /comments/new
  def new
    
    @comment = Comment.new(:parent_id => params[:parent_id], :post_id => params[:post_id])
    @post = Post.find(params[:post_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.user = current_user
    
    if
    @comment.save
    redirect_to @post
      end
  end
  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between action
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
		@post = Post.find(params[:id])
		comments = @post.comments
		comments.map do |comment, sub_comments|
			render(comment) + content_tag(:div, nested_comments(sub_comments), class: "nested_comments")
		end
	end
end

app/views/comments/_comment.html.erb
<% comments.each do |c, children| %>
	<div class="next_level">
		<blockquote>
		  <p><%= c.body %></p>
		  <small class="pull-right reply"><%= link_to 'Reply', new_post_comment_path(id: c.id), remote: true, class: "add_comment#{c.id}" %></small>
		  <small><%= c.created_at.strftime('%d.%m.%Y')%></small>
		</blockquote>
		<%= render 'comment', comments: children if children.present? %>
	</div>		
<% end %>
    

app/views/comments/_form.html.erb
<%= form_for([@post, Comment.new], :html => { :class => 'form-vertical' }) do |f| %>
  <div class="control-group">
    <div class="controls">
      <%= f.text_area :body, rows: 5, placeholder: 'Your comment', class: 'input-block-level' %>
    </div>
  </div>
  <%= f.hidden_field :parent_id, value: params[:id] ? params[:id] : nil, class: '' %>
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Post it!', class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Page for commenting</h1>
<hr>


<p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>
  <p>
    <strong> - </strong>
    <%= @post.body %>
  </p>
  <p>
    <strong>Tags:</strong>
    <%= @post.tags %>
  </p>

  
<%= bootstrap_flash %>
<div class="first_level comment_box">
	<% @post.comments.each do |c| %>
		<div class="next_level">
			<blockquote>
			  <p><%= c.body %></p>
			  <small class="pull-right reply"><%= link_to 'Reply', new_post_comment_path(id: c.id), remote: true, class: "add_comment#{c.id}" %></small>
			  <small><%= c.created_at.strftime('%d.%m.%Y')%></small>
			</blockquote>
			<%= render 'comment', comments: c.descendants.arrange %>
		</div>
	<% end %>
</div>
<div class="root_comment">
	<h4><%= link_to 'Add a comment', new_post_comment_path(id: 0), remote: true, class: 'add_comment0' %></h4>
</div>
<%= render :partial => 'form' %>

<%= link_to 'New Comment', new_post_comment_path(@post.id) %>

app/views/comments/new.html.erb
<div>
<h3>Comments</h3>

<%= render 'form' %>


<p>
<%= link_to 'Main page', posts_path, class: "btn btn-primary" %>
</p>
</div>

app/views/comments/new.js.erb
$('#new_comment').remove();
$('.reply').show();
$('.add_comment<%= params[:id] if params[:id].to_i > 0 %>').parent().hide().parent().after('<%= j render('form') %>');
$('.add_comment<%= params[:id] if params[:id].to_i == 0 %>').parent().after('<%= j render('form') %>');

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>