config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments

    member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
    end
  end

  get 'static_pages/contact' => 'static_pages#contact', as: 'contact'

  get 'static_pages/about' => 'static_pages#about', as: 'about'

  get 'sessions/login'

  get 'sessions/logout' => 'sessions#logout', as: 'sessions_logout'

  post 'sessions' => 'sessions#create'

  resources :posts

  
  get 'registration' => 'users#new', as: 'registration'  # = get 'registration' => 'users#new'

  post 'users' => 'users#create'

  get 'users/:id' => 'users#show'

  resources :users

   root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	
	acts_as_votable
	
	belongs_to :user
	has_many :comments, dependent: :destroy

	
	
	validates_presence_of :title, :body
	validates :title, length: { minimum: 5, maximum: 140 }
	validates :title, uniqueness: true
	validates :body, length: { maximum: 140 }


	def score
  		self.get_upvotes.size - self.get_downvotes.size
  	end
	

	scope :newest, ->  { order( created_at: :desc ) }
    scope :popular, -> { order( voted_rate: :desc ) }
    scope :last_updated, -> { order( updated_at: :desc ) }

    after_create :update_post
  
  def update_post
    self.touch
  end

	#validates :user_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :check_post_user, only: [:edit, :update, :destroy]
skip_before_action :verify_authenticity_token
  
  	def upvote
  		@post = Post.find(params[:id])
    @post.upvote_from current_user
    @rating = @post.get_likes.size - @post.get_dislikes.size
    @post.save
    redirect_to root_path
  end


  def downvote
  	@post = Post.find(params[:id])
    @post.downvote_from current_user
    @rating = @post.get_likes.size - @post.get_dislikes.size
    @post.save
    redirect_to root_path
  end

  def votes
    @post = Post.find(params[:post_id])
    if params[:vote] == '+'
      @post.upvote_from current_user
      @rating += 1
      @post.save
    elsif params[:vote] == '-'
      @post.downvote_from current_user
      @post.rating -= 1
      @post.save
    end
  end



	def index
		if params[:sort] == 'popular'
	      @posts = Post.popular
	    elsif params[:sort] == 'acitve'
	      @posts = Post.active
	    else
		#@posts = Post.paginate(:page => params[:page], :per_page => 6)
    	@posts = Post.paginate(:page => params[:page], :per_page => 2)
    	@number = current_user.posts.count if current_user

    	respond_to do |format|
	      format.html
	      format.json {
	        render json: @posts.to_json(only: [:id, :body, :tags], include: {user: {only: :name}})
	      }

		@users = User.all
	end
    	end
	end


	# GET /posts/1
	def show
		#@user = User.find(params[:id])
		#@posts = Post.where(user_id: @user.id)
		@posts = Post.all
		@comments = @post.comments
			respond_to do |format|
		      format.html
		      format.json {
		        render json: @post.to_json(except: [:updated_at, :user_id], include: {user: {only: :name}})
	          }
        end
	end
	# GET /posts/new
	
	def new
	  @post = Post.new
	end
	# GET /posts/1/edit
	def edit
		@post = Post.find(params[:id])
      unless current_user?(@post.user)
        redirect_to :back
        flash[:notice] = 'You can not edit this post'
      end
	end

	# POST /posts
	def create
	  @post = Post.new(post_params)
	  @post.user_id = current_user.id
	  @post.user = current_user
	  
		 if @post.save
		 	redirect_to @post, notice: 'Post was successfully created.'
		 else
		   render :new
		end
    end
	# PATCH/PUT /posts/1
	def update
		@post = Post.find(params[:id])
	  if @post.update(post_params)
	    redirect_to @post, notice: 'Post was successfully updated.' #redirect_to post_path(@post) OR redirect_to post_path(params[:id])
	  else
	    render :edit
	  end
	end
	# DELETE /posts/1
	def destroy
        @post = Post.find(params[:id])
      unless current_user?(@post.user)
        redirect_to :back
        flash[:notice] = 'You can not delete this post'
      else
        @post.destroy
        respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def popular_posts
    @posts = Post.popular
  end

  def active_posts
    @posts = Post.active_posts
  end

	

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_post
	  @post = Post.find(params[:id])
	end

	def check_post_user
	    unless current_user == @post.user
	      redirect_to root_path
	    end
    end
	
	# Only allow a trusted parameter "white list" through.
	def post_params
	  params.require(:post).permit(:title, :body, :tags)
	end

end

app/helpers/posts_helper.rb
module PostsHelper
	def nested_comments(comments)
		@post = Post.find(params[:id])
		comments = @post.comments
		comments.map do |comment, sub_comments|
			render(comment) + content_tag(:div, nested_comments(sub_comments), class: "nested_comments")
		end
	end

end

app/views/posts/_comment.html.erb
<%= simple_form_for(@comment) do |f| %>
 
  <div class="form-inputs">
  	<%= f.input :body %>
  </div>

  <div class="form-actions">
  	<%= f.button :submit %>
  </div>
  <% end %>

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br
      = f.text_field :title
  .field
    = f.label :body
    %br
      = f.text_area :body
  .field
    = f.label :tags
    %br
      = f.text_field :tags
  .actions
    = f.submit :class => "btn btn-primary"

app/views/posts/_post.html.erb
<table>
        <tr>
          <td><%= image_tag avatar_url(post.user) %></td>
          <td>Posted by: <strong><%= post.user.name.capitalize if post.user %></strong></td>
        </tr>
      </table>

    <p><strong><%= link_to "#{post.title.capitalize}", post %></strong></p>
    <p><strong> - </strong><%= post.body %></p>
    <p><strong>Tags:</strong><%= post.tags %></p>
     
      <table id="tab">
        <tr>
            <td bgcolor="#CCCC99"><%= link_to 'Follow', post %></td>
            <td bgcolor="#CCCCCC"><%= link_to 'Edit', edit_post_path(post) if current_user && current_user.id == post.user.id %></td>
            <td bgcolor="#CCCCFF"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } if current_user && current_user.id == post.user.id %></td> 
        </tr>
      </table>
 <hr>     

    <%= link_to "like", like_post_path(post), method: :put %>
    |
    <%= link_to "dislike", dislike_post_path(post), method: :put %>
    <%= post.score %>

    <p><%= link_to 'Comments', post_path(post) %>: <%= post.comments.length %></p>
     <hr> 

app/views/posts/create.js.erb
$('tab').append('<%= j render partial: 'post', locals: {post: @post} %>');
$('.new_post').remove();

app/views/posts/edit.html.haml
%h1 Editing post
= render :partial => "form"
= link_to 'Show', @post
|
\#{link_to 'Back', posts_path}

app/views/posts/index.html.erb
<div id='paginator'>
<%= will_paginate if @posts.any? %>
<%= page_entries_info @posts %><br/>
</div>


<!-- <div class="popular">
  <%= link_to 'Show Popular', posts_path(popular: 'true') %>
  |
  <%= link_to 'Last Updated', posts_path(last_updated: 'true') %>

</div> -->

<h1>Listing posts</h1>
<ul class="list-group"> 
  <li class="list-group-item active"> Author online:<%= link_to current_user.name.capitalize, user_path(current_user.id) if current_user %>
  <span class="badge">Total posts:<%= @number %></span></li>
</ul>
<hr>

<div>
  <% @posts.each do |post| %>
 
      <table>
        <tr>
          <td><%= image_tag avatar_url(post.user), class: 'avatar' %></td>
          <td>Posted by: <strong><%= post.user.name.capitalize if post.user %></strong></td>
        </tr>
      </table>
  <div id="poster">
    <p><strong><%= link_to "#{post.title.capitalize}", post %></strong></p>
    <p><strong> - </strong><%= post.body %></p>
    <p><strong>Tags:</strong><%= post.tags %></p>
    <p><strong>Rating:</strong><%= post.score %></p>
  </div>
     
      <table id="tab">
        <tr>
            <td bgcolor="#CCCC99"><%= link_to 'Follow', post %></td>
            <td bgcolor="#CCCCCC"><%= link_to 'Edit', edit_post_path(post) if current_user && current_user.id == post.user.id %></td>
            <td bgcolor="#CCCCFF"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } if current_user && current_user.id == post.user.id %></td> 
        </tr>
      </table>
 <hr>     

    <%= link_to "+", like_post_path(post), method: :put %>
    |
    <%= link_to "-", dislike_post_path(post), method: :put %>
    <span class="badge"><%= post.score %></span>

    <p><%= link_to 'Comments', post_comments_path(post) %>: <%= post.comments.length %></p>
     <hr> 
  <% end %>

<h3 class='new_post'><%= link_to 'New post', new_post_path if current_user %></h3>
</div>


<p>Total views: <%= cookies[:views] %></p>

<div id='paginator'>
<%= will_paginate %>
</div>

app/views/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path 

app/views/posts/new.js.erb
$('#new_post_link').after('<div><%= j render 'form' %></div>');

app/views/posts/show.html.erb
    <table>
      <tr>
        <td><%= image_tag avatar_url(@post.user), class: 'avatar' %></td>
        <td>Posted by: <strong><%= @post.user.name.capitalize if @post.user %></strong></td>
      </tr>
    </table>

<div id="poster">
  <p id="notice">
    <%= notice %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>
  <p>
    <strong> - </strong>
    <%= @post.body %>
  </p>
  <p>
    <strong>Tags:</strong>
    <%= @post.tags %>
  </p>
  <p><%= @post.created_at.strftime('%d/%m/%Y') %></p>
  <%= link_to 'Edit', edit_post_path(@post) if current_user && current_user.id == @post.user.id %>
  |
  <%= link_to 'Back', posts_path %>
</div>

 <%= raw("<h3>Comments</h3>") if current_user %>
<% @post.comments.each do |comment| %>
    <div id="comments">
<%= image_tag avatar_url(comment.user) %>
    <p><strong><%= comment.user.name.capitalize %>:</strong></p>  
    <p><strong> - </strong><%= comment.body %></p>
    </div>
    <!-- <%= link_to 'Reply', new_post_comment_path(@post.id, :parent_id => comment) %> |
     <%= link_to 'Delete', [@post, comment], method: :delete, data: { confirm: 'Вы уверены?' } %> -->
<% end %>


 
  <% if current_user %>
  <h3>Add a comment:</h3>
      <%= simple_form_for [@post, Comment.new] do |f| %>
      <p>
        <%= f.input :body, placeholder: 'New Comment' %>
        <%= f.hidden_field :post_id, :value => @post.id %>
      </p>
      <p><h4><%= f.submit "Add Comment", class: "btn btn-primary" %></h4></p>
    <% end %>
  <% end %>

  <h3><%=  link_to 'New Post', new_post_path if current_user %></h3>
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>
</div>
<hr>