config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments

    member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
    end
  end

  get 'static_pages/contact' => 'static_pages#contact', as: 'contact'

  get 'static_pages/about' => 'static_pages#about', as: 'about'

  get 'sessions/login'

  get 'sessions/logout' => 'sessions#logout', as: 'sessions_logout'

  post 'sessions' => 'sessions#create'

  resources :posts

  
  get 'registration' => 'users#new', as: 'registration'  # = get 'registration' => 'users#new'

  post 'users' => 'users#create'

  get 'users/:id' => 'users#show'

  resources :users

   root 'posts#index'

end

app/views/layouts/_banner.html.erb
<div id="banner">
<% if banner_show %>
    <center>
      
      <h3>Let's learn togather with GH </h3>
      <%= link_to image_tag('geekhub.png'), 'http://geekhub.ck.ua/' %>
      <h5 id="close">Close</h5>
    </center>
    <br>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  All rights reserved C.
</div>

app/views/layouts/_header.html.erb
<div id="header">	
  <ul class="nav nav-tabs" role="tablist">
    <% if current_user %>
      <li role="presentation"><%= link_to 'Logout', sessions_logout_path %></li>
    <% else %>
      <li role="presentation" class="active"><%= link_to 'Login', sessions_login_path %></li>
      <li role="presentation"><%= link_to 'Registration', registration_path %></li>
<% end %>

  </ul>
  <h1 style="color: #00ff00;"><%= link_to 'Mini Blog', root_path %></h1>   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/banner' %>
	<%= render 'layouts/header' %>

  

<div id="nav">
	 <h3><%= link_to 'Menu', root_path %></h3> 
	   <ul class="nav nav-pills nav-stacked" role="tablist">
      <li role="presentation" class="active"> <%= link_to "My profile", user_path(current_user.id) if current_user %></li>
         <li role="presentation"><%= link_to 'Main page', root_path %></li>
         <li role="presentation"><%= link_to 'Contacts', contact_path%></li>
         <li role="presentation"><%= link_to 'About us', about_path%></li>
       </ul>
</div>



<div id="section">
  <%= yield %>
</div>
	

	<%= render 'layouts/footer' %>

</body>
</html>